message.json

Add device message spec to REC repo.
To start with just a JSON file, later on possibly defined by other means.

2.3 with message

---

lantmäteriet.rdf

Hej Karl, första försök på ett Fastighetsregistermodul
Det finns ett antal grejer att tänka igenom och fixa. Bra om vi kan ta en review senare när du har haft tid att merge och se igenom.
En grej slog mig. Jag har gjort en Apartment klass. Fast kanske denna bör bli en sub klass på nya Collection eller på nya Apartment under Collection. Blir i alla fall lite konstigt med flera Apartments så vi måste tänka igenom. Kanske endast addera relevant properties på befintlig Apartment klass. Låt os diskutera detta för jag modellerar klar lägenheten.
Hörs, 
Mvh Peter

Lantmäteriet

---

api/edge_messages/edge_message.schema.json
api/edge_messages/edge_message_cloud-to-edge_example.json
api/edge_messages/edge_message_edge-to-cloud_example.json

Re-structure edge message example, separating between edge-to-cloud and cloud-to-edge (same structure as in the README)

Fix edge message example to follow spec for 3.1.1

---

ontology/building.rdf

one minor error that prevented import of the Building ontology.

Fix version IRI of Building module.

---

ontology/alignments/REC-BOT-alignment.ttl

Synced with work in the BOT group, see https://github.com/w3c-lbd-cg/bot/pull/79

Added alignment to BOT

---

ontology/core.rdf

Re-implemented Premises classes and individuals

---

ontology/core.rdf
ontology/device.rdf

Revert property renaming

---

ReleaseNotes.md
ontology/full.rdf
ontology/lfr.rdf

Since we'll simply hotfix 3.2 in place w/ the new LFR serialized name.

Removed 3.2.1 release notes

---

README.md

changed joint our chat to join our chat

---

ontology/core.rdf
ontology/device.rdf

Added basic tagset representation, providing a possible bridge to tag/point-based systems. Logic: Capability --tags--> CapabilityTagSet --(various data properties representing tags)--> indvidual tag values

Feature tags

---

ontology/building.rdf

MezzanineLevel, RoofLevel, BasementLevel
LockerRoom ,NurseryRoom
HospitalRoom: AdmittingRoom, Morgue, , OperatingRoom, OutpatientServicesRoom, PharmacyRoom, RadiologyRoom, TherapyRoom

Added new level and room types

---

ontology/device.rdf

These can instead be modelled using Capability.categorizationProperties.assetComponent = Valve or Damper

Removed Valve and Damper open setpoint/sensor

---

ontology/core.rdf

Adding relationships from DTDL models on our top-level classes. This is strictly additive and seems to make sense also in a REC-OWL context.

Feature update top level relationships

---

ontology/device.rdf

See DTDL PR https://github.com/Azure/opendigitaltwins-building/pull/65

Added lastValue typing on BinaryState / PercentState

---

Doc/Space/Architecture/Level/Level.md
Ontology/DTDLv2/RealEstateCore/Space/Architecture/Level/Level.json
Ontology/SHACL/RealEstateCore/rec.ttl

This closes #153 in accordance with TC decision October 5
Review + merge requested from TC membership

Update levelNumber description

---

Ontology/DTDLv2/Brick/Point/Sensor/Frost_Sensor.json
Ontology/DTDLv2/Brick/Point/Sensor/Temperature_Sensor/Temperature_Sensor.json
Ontology/SHACL/IgnoredInTranslationToDTDL.csv

This is a bugfix to get lastKnownValue working properly on Temperature_Sensor

Deprecated Frost_Sensor extends Temperature_Sensor

---

Source/DTDLv2/RealEstateCore/Agent/Agent.json
Source/SHACL/RealEstateCore/rec.ttl
Tools/DTDL2MD/DigitalTwinsParserExtensions.cs
Tools/DTDL2MD/Program.cs

Feature: Agent.owns + documentation of general (untargeted) Relationships

---

Tools/DTDL2MD/DigitalTwinsParserExtensions.cs
Tools/DTDL2MD/Program.cs
Tools/DTDLMerger/Program.cs

/Tools fixes

---

Tools/DTDLMerger/DtdlMerger.csproj
Tools/DTDLMerger/Program.cs
Tools/DTDLValidator/DTDLValidator.csproj
Tools/DTDLValidator/Program.cs

Updated the tools to the latest DTDL Parser
Built and ran the DTDLMerger
Ran validator

Updating to latest nugets

---

OntologyDecisionRecords/000 Use of Ontology Decision Records (ODR).md
OntologyDecisionRecords/ODR 000: Use of Ontology Decision Records (ODRs).md
OntologyDecisionRecords/ODR 001: Naming Conventions.md
README.md

I've been using "Ontology Decision Records" for extension my teams are making to REC. I think this process might also work for REC to engage with the community and capture not just the decisions, but the context and alternatives considered at the time the decision was made.

Initial draft of ODR proposal

---

Source/DTDLv2/RealEstateCore/Space/Architecture/Room/Lobby.json
Source/DTDLv2/RealEstateCore/Space/Architecture/Room/Lounge.json
Source/DTDLv2/RealEstateCore/Space/Architecture/Room/Team-.json

Adds TeamRoom and Lobby to the room taxonomy. Both as direct sub classes to rec:Room.

Added missing rooms (closes #242)
